# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet


- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
    
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'ServUO_SonarCloud'
    organization: 'trueuo'
    scannerMode: 'MSBuild'
    projectKey: 'trueuo'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
  displayName: 'dotnet build $(solution)'
    
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
